package environment

var (
	ENV_KEY_MONGO_DB_USER = "MONGO_DB_USER"
	ENV_KEY_MONGO_DB_PW = "MONGO_DB_PW"
	ENV_KEY_MONGO_DB_NAME= "MONGO_DB_NAME"
	ENV_KEY_MONGO_ID = "MONGO_ID"
	ENV_KEY_DB_TIMEOUT = "MONGO_DB_TIMEOUT"
	ENV_KEY_ENABLE_2FA = "ENABLE_2FA"
	ENV_KEY_PORTAL_DOMAIN = "PORTAL_DOMAIN"
)
