package environment

var (
	//********AWS service store
	// quote-service  will have specific env variables

	ENV_KEY_POSTGRESQLHOST     = "POSTGRESQLHOST"
	ENV_KEY_POSTGRESQLPORT     = "POSTGRESQLPORT"
	ENV_KEY_POSTGRESQLUSER     = "POSTGRESQLUSER"
	ENV_KEY_POSTGRESQLPASSWORD = "POSTGRESQLPASSWORD"
	ENV_KEY_POSTGRESQLDBNAME   = "POSTGRESQLDBNAME"
)
