package environment

var (
	ENV_KEY_BATCH_LIMIT                = "BATCH_LIMIT"
	ENV_KEY_KAFKA_ENABLE_SSL           = "KAFKA_ENABLE_SSL"
	ENV_KEY_KAFKA_ENABLE_SASL          = "KAFKA_ENABLE_SASL"
	ENV_KEY_KAFKA_CA_LOCATION          = "KAFKA_CA_LOCATION"
	ENV_KEY_KAFKA_CERTIFICATE_LOCATION = "KAFKA_CERTIFICATE_LOCATION"
	ENV_KEY_KAFKA_KEY_LOCATION         = "KAFKA_KEY_LOCATION"
	ENV_KEY_KAFKA_KEY_PASSWORD         = "KAFKA_KEY_PASSWORD"
	ENV_KEY_KAFKA_KEY_SASL_USER        = "KAFKA_KEY_SASL_USER"
	ENV_KEY_KAFKA_KEY_SASL_PASSWORD    = "KAFKA_KEY_SASL_PASSWORD"
	ENV_KEY_KAFKA_KEY_SASL_MECHANISM   = "KAFKA_KEY_SASL_MECHANISM"
	ENV_KEY_KAFKA_BROKER_URL           = "KAFKA_BROKER_URL"
	ENV_KEY_MESSAGE_RETRIEVE_TIMEOUT   = "MESSAGE_RETRIEVE_TIMEOUT"
)
