# Quotes Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ww-quotes
  namespace: default
  labels:
    app: ww-quotes
    type: global
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ww-quotes
  template:
    metadata:
      labels:
        app: ww-quotes
        type: global
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: sandbox-ww-global
      containers:
      - env:
        - name: SERVICE_NAME
          value: "quotes-service"
        - name: HOME_DOMAIN_NAME
          value: "ww"
        image: jp.icr.io/dapww/quotes-service:latest
        imagePullPolicy: Always
        name: ww-quotes
        ports:
        - containerPort: 8083
        envFrom:
        - configMapRef:
            name: env-config-global
        - secretRef:
            name: vault-cert
      restartPolicy: Always