# Whitelist Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ww-whitelist
  namespace: default
  labels:
    app: ww-whitelist
    type: global
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ww-whitelist
  template:
    metadata:
      labels:
        app: ww-whitelist
        type: global
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: sandbox-ww-global
      containers:
      - env:
        - name: SERVICE_NAME
          value: "whitelist-service"
        - name: HOME_DOMAIN_NAME
          value: "ww"
        image: jp.icr.io/dapww/global-whitelist-service:latest
        imagePullPolicy: Always
        name: ww-whitelist
        ports:
        - containerPort: 11234
        - containerPort: 21234
        envFrom:
        - configMapRef:
            name: env-config-global
        - secretRef:
            name: vault-cert
      restartPolicy: Always
