# Payment Listener Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: participant_id_variable-listener
  labels:
    app: participant_id_variable-listener
    type: mm
    id: participant_id_variable
spec:
  replicas: replica_variable
  selector:
    matchLabels:
      app: participant_id_variable-listener
  template:
    metadata:
      labels:
        app: participant_id_variable-listener
        type: mm
        id: participant_id_variable
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: sandbox-ww-participant_id_variable
      containers:
      - env:
        - name: SERVICE_NAME
          value: "payment-service"
        - name: HOME_DOMAIN_NAME
          value: "participant_id_variable"
        image: jp.icr.io/dapww/payment-listener:docker_tag_variable
        imagePullPolicy: Always
        name: participant_id_variable-listener
        resources:
          requests:
            memory: "64Mi"
            cpu: "0.1"
          limits:
            memory: "128Mi"
            cpu: "0.25"
        ports:
        - containerPort: 11005
        - containerPort: 21005
        envFrom:
        - configMapRef:
            name: env-config-global
        - secretRef:
            name: vault-cert-participant_id_variable
        - secretRef:
            name: kafka-secret-participant_id_variable
      restartPolicy: Always