apiVersion: v1
kind: Service
metadata:
  name: ww-auth
  namespace: default
  labels:
    app: ww-auth
    service: ww-auth
spec:
  ports:
    - name: external
      port: 6001
  selector:
    app: ww-auth
---