apiVersion: v1
kind: Service
metadata:
  name: ww-portal
  labels:
    app: ww-portal
    service: ww-portal
spec:
  ports:
    - name: external
      port: 4200
  selector:
    app: ww-portal
---
apiVersion: v1
kind: Service
metadata:
  name: ww-portal-api
  namespace: default
  labels:
    app: ww-portal-api
    service: ww-portal-api
spec:
  ports:
    - name: external
      port: 8686
  selector:
    app: ww-portal-api