apiVersion: v1
kind: ServiceAccount
metadata:
  name: role_name_variable
  namespace: default
imagePullSecrets:
  - name: default-icr-io
  - name: default-us-icr-io
  - name: default-uk-icr-io
  - name: default-de-icr-io
  - name: default-au-icr-io
  - name: default-jp-icr-io
  - name: all-icr-io