[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.da1]
    NODE_ADDRESS = "GBTJVFAAZCRJG4TXAMADCBDQ6RJGYJJ34XAJLONUSQA5YCPB2356IUBJ"
    NODE_SEED = "SASST6R5TNKUOEZ6ONX25CWW6X2TWXV5CIN4GORQW7J6NZVTGKGV7EW3"

  [DISTRIBUTION_ACCOUNTS.da2]
    NODE_ADDRESS = "GDSVFKYAC6KKREKYYZA7RMGKDC6JXNA35IDT5PKGB3UHWYFIR7U4LXMG"
    NODE_SEED = "SCP57PHPEAUGL6PETIYMDBN5XVJAZJ3J5WOB6DCC42HT7FIKCMQFL2ZP"

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GA7D2ZZHDRELM7G3DVXSNYGLXPTMFVHTJOQZ3SKSCBDR7DHPPAQS2OW6"
    NODE_SEED = "SBGIHXUJE4M5I67W2EX727N5YLASFVRN3K2YBKIH3TWLR3I2I52IWDPF"
  [DISTRIBUTION_ACCOUNTS.tom1]
    NODE_ADDRESS = "GCBAHUHTU4TJ5KXOTONCW4MJQEOMAOHPCINURDWQO6AUBFBNZJHVYXP7"
    NODE_SEED = "SCSWIIIPYFNPEON5FA67ZTSTCYGTTD3TGD3LZ72FXZGYGZW4KKONQFBV"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GBSWQMTC4MCYLN2XSCXM7ZQL3XPPD2K52YD7GED33T6DHAPHKDFUMI7P"
  NODE_SEED = "SDPJDYOV4U6EZUD6QO4I54E6OCUGE3ZWKWST3EP7CBZJCLHM6ZZLTCFI"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GCXLJMLJXRZIMPT2GI2L5IMSLDZKMCG6QX62BHAPAQLQIVFHOTHM5W4B"
  NODE_SEED = "SABD4YXSXRNGRPNOUV2MK7GO5K2GYE56OESZN6HPEWCSJFLPCUYLFHBD"
