
[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GAM5QC6M26ZWMOZZL6SANRZ6RGYAWRQJDEWBALHYZWWGIUCVAGAJD4ZF"
    NODE_SEED = "SDUCJIY7MLPNJ5L3W7OLSN64Z6VFM4Y32NKZB6UF6ZU73B5SZ562TDGN"

  [DISTRIBUTION_ACCOUNTS.sagu]
    NODE_ADDRESS = "GCPB2TJK4CHAXESIGZIHVJMBQ2SK4I6UUKHPU7BWL7MCJF3ESC7SZ6TG"
    NODE_SEED = "SA5MFAPVIN4TAYF6FQHXOQJIDI25NK5YMFTD2HPWYQ75ORBLBOGPZ2WI"

  [DISTRIBUTION_ACCOUNTS.seema]
    NODE_ADDRESS = "GBJT2KDHBTNRNZVCFPWLDIMUSJTRU5SZIDXJCGIKLGX5F2DYTXJE2BS2"
    NODE_SEED = "SDJQBKAD3YECROKQQENGSCEG4MW5NLERENLENAQ7PVWRPFEM35TMWU7V"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GAGDTJA5R2UURAYTYWRSN6PFIIIVOBFIPDZUQN7XLVRIMNOCBAXC4JYV"
  NODE_SEED = "SAIQ3ZKBDMFSQHT7PJB4BALFFI2AMAV57ORFFTV4KIGYG2O3Z7SAWOHM"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GCZN5K3MKKTYHZ6RLOJHOH3W7WUIKSYCOZXFJYF6DWGWEPEGAS4MTPIV"
  NODE_SEED = "SA2VINNOUIUFRV5JQN3K4GBEHE4VM6EVPNQP2GZIXDDBLONXTTSIVHGW"