[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.da1]
    NODE_ADDRESS = "GDBIAFVTAUBPP3MNNXPED3BDAE6E7BBLS537ZS2NEE27P6H3SRJMN7CH"
    NODE_SEED = "SDQIGX5HLF3FD6DJ4FDMDAGSE45CJ2GIASQTRNWFUFQOZLJWK65BNXC6"

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GDPCVTQQH423VSBLM6VAJOCEKU2PT5MCZNDL7PNMMJTCCJA3O56ORGXD"
    NODE_SEED = "SAGMPARG7OTZHIC4IL5KHI4UXQ73KRP7QXQ3XB3PAE55ASK7XE3773PJ"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GBSWQMTC4MCYLN2XSCXM7ZQL3XPPD2K52YD7GED33T6DHAPHKDFUMI7P"
  NODE_SEED = "SDPJDYOV4U6EZUD6QO4I54E6OCUGE3ZWKWST3EP7CBZJCLHM6ZZLTCFI"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GDNTT3VZN7KASCNETM7SC4BB5KHG6MUPZVKFV6FSVMERHAWLQTX7WM5L"
  NODE_SEED = "SB4Q7MEUCV2QT7DV7YLOIOYUN5MDO5OA26TIBNJFHSXVJW3UJ66O2OEM"

[WHITE_LIST]
  PARTICIPANT_DOMAINS = "sg.one.payments.gftn.io"
