
[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.DA1]
    NODE_ADDRESS = "GCDQYLY7QH7YMVRJVGRGT5LKMRQLREMQYLCVZZVP3REFIDN2UEVX5LTH"
    NODE_SEED = "SAZSMTEBZPAITJ7WI2T7IPJPAI2ITSN5MTNN7FP4ZBZCZYZM2JRQDIHD"

  [DISTRIBUTION_ACCOUNTS.OperatingAcc1]
    NODE_ADDRESS = "FakeOperatingAccount1NodeAddr"
    NODE_SEED = "Secret1"

  [DISTRIBUTION_ACCOUNTS.OperatingAcc2]
    NODE_ADDRESS = "FakeOperatingAccount2NodeAddr"
    NODE_SEED = "Secret2"

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "FakeOperatingAccountDefaultNodeAddr"
    NODE_SEED = "SecretDefault"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "FakeIBMAcc"
  NODE_SEED = "SA2VINNOUIUFRV5JQN3K4GBEHE4VM6EVPNQP2GZIXDDBLONXTTSIVHGW"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "FakeIssuingAccount"
  NODE_SEED = "SC4TZ5VOZ3P4L4NKQ4I54YKW57DVZU5STS2ZMFJUVQP7LB6LYZOCPH7C"

[WHITE_LIST]
  PARTICIPANT_DOMAINS = ""
