
[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.doesntexist]
    NODE_ADDRESS = "FakeOperatingAccount"
    NODE_SEED = "SDJQBKAD3YECROKQQENGSCEG4MW5NLERENLENAQ7PVWRPFEM35TMWU7V"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "FakeIBMAcc"
  NODE_SEED = "SA2VINNOUIUFRV5JQN3K4GBEHE4VM6EVPNQP2GZIXDDBLONXTTSIVHGW"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "FakeIssuingAccount"
  NODE_SEED = "SC4TZ5VOZ3P4L4NKQ4I54YKW57DVZU5STS2ZMFJUVQP7LB6LYZOCPH7C"
