
[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.doesntexist]
    NODE_ADDRESS = "FakeOperatingAccount"
    NODE_PASS_CODE = ""
    NODE_SEED = "SDJQBKAD3YECROKQQENGSCEG4MW5NLERENLENAQ7PVWRPFEM35TMWU7V"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GBSWQMTC4MCYLN2XSCXM7ZQL3XPPD2K52YD7GED33T6DHAPHKDFUMI7P"
  NODE_PASS_CODE = ""
  NODE_SEED = "SDPJDYOV4U6EZUD6QO4I54E6OCUGE3ZWKWST3EP7CBZJCLHM6ZZLTCFI"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GDSETWFTRLQ6TUSAOKMEY3K2ZDVAPB5BBWFMQ6DIUYDZANPI5UPEUTEA"
  NODE_PASS_CODE = "3f7d8a6eaa76dba8a52ebd5349f8419d343d0f76541b6f94af36a83774b561595f3615dd99ae6e9e681f3d85246ad8b622e841f03ff177bdf9728795d138a893"
  NODE_SEED = "SALFSC2TLFB53WB3BSUWHBJBULCDITFO7WUELUYIXXGJ4X7VUPUVU4QN"

[WHITE_LIST]
  PARTICIPANT_DOMAINS = ""
