[DISTRIBUTION_ACCOUNTS]

 [DISTRIBUTION_ACCOUNTS.default]
   NODE_ADDRESS = "GCUIXHQV3VOVGBKJLOMI5NBHDBTNQ6A5IQXCSENVZ3OU63FSTMFRZ2H2"
   NODE_SEED = "SCLUQ7PXMOHIQ24MAWPHTX4NVITDRXVKRCA7KP3NABBA7AQ3F3VOIA2R"
 [DISTRIBUTION_ACCOUNTS.test1]
   NODE_ADDRESS = "GASCCP5TACQKI3SVMADRDKCLUNO4UOFGXNHYFNO7ONLIA3VZGYC3LVLJ"
   NODE_SEED = "SAUKS5TVM3NSDHU7OG44WV6KMA2A64WHZV76ACICSTTTTYPN2AM7G5AH"

[IBM_TOKEN_ACCOUNT]
 NODE_ADDRESS = "GBSWQMTC4MCYLN2XSCXM7ZQL3XPPD2K52YD7GED33T6DHAPHKDFUMI7P"
 NODE_SEED = "SDPJDYOV4U6EZUD6QO4I54E6OCUGE3ZWKWST3EP7CBZJCLHM6ZZLTCFI"


[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GDHN4EOLOYSOZXGZK2LALH4FXFI33OAOP5XHIRNF65EIJPY7KAWOULH6"
  NODE_PASS_CODE = "554e6f884f11b65b51e327598631f52ceac18d2591e0d52f66b3fa6b57c5fe7de8f640c47e81267fa3e13fa076c1f83526fc6fbf4e763e592d368292df909990"
  NODE_SEED = "SCB2WTVAG5XHBKT6MP5EYP262MZ7TBLKTNJEF24NEKWYTW7ARXRFEG6V"


[WHITE_LIST]
 PARTICIPANT_DOMAINS = "au.one.payments.gftn.io"