
[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GAM5QC6M26ZWMOZZL6SANRZ6RGYAWRQJDEWBALHYZWWGIUCVAGAJD4ZF"
    NODE_SEED = "SDUCJIY7MLPNJ5L3W7OLSN64Z6VFM4Y32NKZB6UF6ZU73B5SZ562TDGN"

  [DISTRIBUTION_ACCOUNTS.sagu]
    NODE_ADDRESS = "GCPB2TJK4CHAXESIGZIHVJMBQ2SK4I6UUKHPU7BWL7MCJF3ESC7SZ6TG"
    NODE_SEED = "SA5MFAPVIN4TAYF6FQHXOQJIDI25NK5YMFTD2HPWYQ75ORBLBOGPZ2WI"

  [DISTRIBUTION_ACCOUNTS.seema]
    NODE_ADDRESS = "GBJT2KDHBTNRNZVCFPWLDIMUSJTRU5SZIDXJCGIKLGX5F2DYTXJE2BS2"
    NODE_SEED = "SDJQBKAD3YECROKQQENGSCEG4MW5NLERENLENAQ7PVWRPFEM35TMWU7V"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GC3ZBVI7VKIGNNHZQ54ZJSORIZQHVQUTJ5CY2I4BRM4MLO6UHBSZXJ74"
  NODE_SEED = "SASCR3VKOI6HP7YSLEYNGGFYMYVCQQ7F7LE7JVXY3J6BYRFSD5A3TUF4"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GBSWQMTC4MCYLN2XSCXM7ZQL3XPPD2K52YD7GED33T6DHAPHKDFUMI7P"
  NODE_PASS_CODE = ""
  NODE_SEED = "SDPJDYOV4U6EZUD6QO4I54E6OCUGE3ZWKWST3EP7CBZJCLHM6ZZLTCFI"
