// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BlocklistReq BlocklistRequest
// swagger:model BlocklistReq
type BlocklistReq struct {

	// approval Id
	// Required: true
	ApprovalID *string `json:"approvalId" validate:"required"`

	// type
	// Required: true
	Type *string `json:"type" validate:"required"`

	// value
	// Required: true
	Value *string `json:"value" validate:"required"`
}

// Validate validates this blocklist req
func (m *BlocklistReq) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateApprovalID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BlocklistReq) validateApprovalID(formats strfmt.Registry) error {

	if err := validate.Required("approvalId", "body", m.ApprovalID); err != nil {
		return err
	}

	return nil
}

func (m *BlocklistReq) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

func (m *BlocklistReq) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BlocklistReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BlocklistReq) UnmarshalBinary(b []byte) error {
	var res BlocklistReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
