[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GADCW4YOX3B4QH6R4KLUZHUZJ4U243XYDPL4UV2SZGBIC2DI2IKEQUII"
    NODE_SEED = "SDWFVELL3DPDEOFZYEJYX4NYMEBTPHLFFVBZ22BJ32FXXE3YSCGHM7EU"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GBSWQMTC4MCYLN2XSCXM7ZQL3XPPD2K52YD7GED33T6DHAPHKDFUMI7P"
  NODE_SEED = "SDPJDYOV4U6EZUD6QO4I54E6OCUGE3ZWKWST3EP7CBZJCLHM6ZZLTCFI"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GAYVH6X3DGH7D7ZQY2PUUZV2RT2EUEULSEWOFDSTE7IC3S3QLT6H262F"
  NODE_SEED = "SCRGOJCX2JGRUWVRUU6IRMULTPC5FLWV3SAQCAMO6H6IFFM26UPBZS25"
