
[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GC42RQF6NC7ZQ4JM4EBZHYBDZRKBCVGKQTD5XY2WRKJSRF2ZJUKERV7T"
    NODE_PASS_CODE = ""
    NODE_SEED = "SCRP76PV4EPCEXEICIW5WX2AJV7WT3WWJVQNKQF3JHZ6GSB7XQHTFPBP"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GD2RP3XK2AU2NMMG5AIXBBIZVPGKBUZVKIUTT5NCXG6LHD6FFN7UJGW2"
  NODE_PASS_CODE = ""
  NODE_SEED = "SA7CA742PJG3NRRMWSNGTCV2OWUIZSBIC2COVLINWWGPT4PG3VVRMFLV"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GA3Z5DS6GAPBI6EGRFRCEJKAFBZHESW62U5ME3OJYVD5VEREY5ENTGIK"
  NODE_PASS_CODE = ""
  NODE_SEED = "SC5HQEXEYBYFQ5ZRJ6IVPWW24EBKZBAYM565JBSXQDI4RGDSYBR72EZE"

[WHITE_LIST]
  PARTICIPANT_DOMAINS = "ie.one.payments.worldwire.io;usd.us.stronghold.co;"
