[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GDTKBZ2AZROVIKRH37A2VNHHC3UADOMBC3IJFF5PJBGB7OJEFTTVIYXL"
    NODE_SEED = "SAMDV2RHIGPLOTPP5ZQZ6IJ2KOGOOV6KN4SWAIEU2C4NW6MNCVDRTL4K"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GBC7RNHM4B4IMO56A2ZJQIN2ZT2FA2VUMEK5UIWZMROLVLGNI4O6Z2WA"
  NODE_SEED = "SCPHWJNTHSQAHQGI6YUSXKCLPERGNECKT23EOKWYXQKYGMXPM4I5WIAY"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GA3R6DKDA2B554KHCQIEJE5FLTXRMRIAD3O236JBUEXLA3764C4D4NKV"
  NODE_SEED = "SC6XE7HXUVJBC7U22PWUSGRIDS5VZHSC4KFXTVN3OHJ6FNZEXUOUQZSK"

[WHITE_LIST]
  PARTICIPANT_DOMAINS = "usd.us.stronghold.co;ie.one.payments.worldwire.io"
