[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GAER34EGTS6GES5Y7HPNP65Y2FDWXI2ENEM4IIDY72UDS6MSKE3MPELN"
    NODE_SEED = "SBU26DAAJZCQUDNY4RHHDEAZUTUIVMNSAVGQP6R3ROJQAOCCVNEL3M2Z"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GBC7RNHM4B4IMO56A2ZJQIN2ZT2FA2VUMEK5UIWZMROLVLGNI4O6Z2WA"
  NODE_SEED = "SCPHWJNTHSQAHQGI6YUSXKCLPERGNECKT23EOKWYXQKYGMXPM4I5WIAY"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GDMD5T5BTXKXF6UWD5HKEJZO32UDPO3IEEV46NZPYIQINM37BK5NMSM3"
  NODE_SEED = "SD5L7Q64NCI4RCNRKGX332R7Y36ENKF4C2FDSWSBCFE32TY4BP6RJ6VA"

[WHITE_LIST]
  PARTICIPANT_DOMAINS = ""

  