
[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GA4BK457SSMZKSXIBBKNPHN5JX3MGM4F46M6FLLA7XBT2N5G6CCWBJT4"
    NODE_SEED = "SBXG4SV2QHC5KCBIYMNXCP7DZ4UU3WLBTZ5VUV7JK5CW7EBMZRHGW6LP"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GBSWQMTC4MCYLN2XSCXM7ZQL3XPPD2K52YD7GED33T6DHAPHKDFUMI7P"
  NODE_SEED = "SDPJDYOV4U6EZUD6QO4I54E6OCUGE3ZWKWST3EP7CBZJCLHM6ZZLTCFI"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GA7Z4F45IDUPK4BJTJC4XOVMT6VNYAQ6TUK35VHCBDVORKZHKA5LR5ZZ"
  NODE_SEED = "SCZQX6ISGQ7BVKQIFANXJGWXL62SWFUTIEOSMW2TDSVWMFZHFHXAXJRL"

[WHITE_LIST]
  PARTICIPANT_DOMAINS = "fj.one.payments.gftn.io;sg.one.payments.gftn.io"
