
[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GCBUP7FPYKPLFHVPFZC76SZBV4IY6K2WNSWBG7IKGP5Q4SXKUMG6URB3"
    NODE_SEED = "SBXLDPU63RLNCYVQKPYMDXNXPK6XZKG2SQ5WFUMLBFDIFJLJP3GKY2S2"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GBSWQMTC4MCYLN2XSCXM7ZQL3XPPD2K52YD7GED33T6DHAPHKDFUMI7P"
  NODE_SEED = "SDPJDYOV4U6EZUD6QO4I54E6OCUGE3ZWKWST3EP7CBZJCLHM6ZZLTCFI"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GD6TEBVZ3ILXMOFFYMN2RUKIYBGBCUOO3M6C4VAAI5Z5WUAXZ5OETTUL"
  NODE_SEED = "SAXSTUU52CTGAVHE6I2O5GHKPJCHESPHNDRHUZFMHOONXKAF7FM5XT2T"

