[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GDMHWOGETYSN6B7AZFP65IXQMUJW7MJZDVMQZGKZSVP2SLUM4BGCVRFH"
    NODE_PASS_CODE = ""
    NODE_SEED = "SDL6YQGJM3HPCWUQCSZXCWGCKDGKEVQ7J5UZUI6QTWAWDR4SANA2MDZO"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GD2RP3XK2AU2NMMG5AIXBBIZVPGKBUZVKIUTT5NCXG6LHD6FFN7UJGW2"
  NODE_PASS_CODE = ""
  NODE_SEED = "SA7CA742PJG3NRRMWSNGTCV2OWUIZSBIC2COVLINWWGPT4PG3VVRMFLV"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GBPD3QEYU5E6ORGOY54WS2BQIFSJBM3GUQQOEPPYB4DZ2B5GQ7QHUVAV"
  NODE_PASS_CODE = ""
  NODE_SEED = "SBNOGNMWZVHZNM2L5NK3BZFYI7SR5QWO4YIFYTETSKSU6X3K7RJD7DEM"

[WHITE_LIST]
  PARTICIPANT_DOMAINS = "usd.us.stronghold.co;hk.one.payments.worldwire.io;picklericks.worldwire.io"
