package environment

var (

	// Environment variables used by this service
	ENV_KEY_DB_USER                       = "DB_USER"
	ENV_KEY_DB_PWD                        = "DB_PWD"
	ENV_KEY_MONGO_ID                      = "MONGO_ID"
	ENV_KEY_PORTAL_DB_NAME                = "PORTAL_DB_NAME"
	ENV_KEY_AUTH_DB_NAME                  = "AUTH_DB_NAME"
	ENV_KEY_TX_DB_NAME                    = "TX_DB_NAME"
	ENV_KEY_INSTITUTION_DB_TABLE          = "INSTITUTION_DB_TABLE"
	ENV_KEY_BLOCKLIST_REQ_DB_TABLE        = "BLOCKLIST_REQ_DB_TABLE"
	ENV_KEY_WHITELIST_REQ_DB_TABLE        = "WHITELIST_REQ_DB_TABLE"
	ENV_KEY_ACCOUNT_REQ_DB_TABLE          = "ACCOUNT_REQ_DB_TABLE"
	ENV_KEY_ASSET_REQ_DB_TABLE            = "ASSET_REQ_DB_TABLE"
	ENV_KEY_TRUST_REQ_DB_TABLE            = "TRUST_REQ_DB_TABLE"
	ENV_KEY_KILLSWITCH_REQ_DB_TABLE       = "KILLSWITCH_REQ_DB_TABLE"
	ENV_KEY_SUPER_APPROVAL_DB_TABLE       = "SUPER_APPROVAL_DB_TABLE"
	ENV_KEY_PARTICIPANT_APPROVAL_DB_TABLE = "PARTICIPANT_APPROVAL_DB_TABLE"
	ENV_KEY_USER_DB_TABLE                 = "USER_DB_TABLE"
	ENV_KEY_JWT_INFO_DB_TABLE             = "JWT_INFO_DB_TABLE"
	ENV_KEY_PAYMENT_DB_TABLE              = "PAYMENT_DB_TABLE"
	ENV_KEY_QUOTE_DB_TABLE                = "QUOTE_DB_TABLE"
	ENV_KEY_DB_TIMEOUT                    = "DB_TIMEOUT"
	ENV_KEY_JWT_SECURE_DB_TABLE           = "JWT_SECURE_DB_TABLE"
	ENV_KEY_PERMISSION_DB_TABLE           = "PERMISSION_DB_TABLE"
)
