[DISTRIBUTION_ACCOUNTS]



[IBM_TOKEN_ACCOUNT]
 NODE_ADDRESS = "GB6KMNQODYL5QGS3NFXAQYNFDK6RSDKWNV4BTPP6AQZTKURUFBB2KMY4"
 NODE_PASS_CODE = ""
 NODE_SEED = "SAC2SAROEQIHY5ITMPUG5XEXPZJAOJBU45EZY2COZFI2IRGABK2CGH7M"
 PrivateKeyLabel = ""
 PublicKeyLabel = ""

[ISSUING_ACCOUNT]


[WHITE_LIST]
 PARTICIPANT_DOMAINS = ""
