
[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GAM5QC6M26ZWMOZZL6SANRZ6RGYAWRQJDEWBALHYZWWGIUCVAGAJD4ZF"
    NODE_SEED = "SDUCJIY7MLPNJ5L3W7OLSN64Z6VFM4Y32NKZB6UF6ZU73B5SZ562TDGN"

  [DISTRIBUTION_ACCOUNTS.sagu]
    NODE_ADDRESS = "GCPB2TJK4CHAXESIGZIHVJMBQ2SK4I6UUKHPU7BWL7MCJF3ESC7SZ6TG"
    NODE_SEED = "SA5MFAPVIN4TAYF6FQHXOQJIDI25NK5YMFTD2HPWYQ75ORBLBOGPZ2WI"

  [DISTRIBUTION_ACCOUNTS.seema]
    NODE_ADDRESS = "GBJT2KDHBTNRNZVCFPWLDIMUSJTRU5SZIDXJCGIKLGX5F2DYTXJE2BS2"
    NODE_SEED = "SDJQBKAD3YECROKQQENGSCEG4MW5NLERENLENAQ7PVWRPFEM35TMWU7V"

  [DISTRIBUTION_ACCOUNTS.sudu]
    NODE_ADDRESS = "GCT4BZS42IKHOE5UGDL4IJ7LE2UYCG4SQHLR7TGUEK6VPFHYYVXVV6EK"
    NODE_SEED = "SCYT7RDRDF6ZXEYURU36JPS722O5XE3D3E5MYUQDC2IC7BBE3OOJZN7T"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GA3UQQ7HQC4JJZCQO5IWZDZRJV2UHY5SS6MOU36H2QSIBNATZAXJZSMK"
  NODE_SEED = "SBBM5B5XJ4BVKNDGVH57NRUB6V23VUGNMRV6RYN7AOGSTLRUAGSJIG6C"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GCZN5K3MKKTYHZ6RLOJHOH3W7WUIKSYCOZXFJYF6DWGWEPEGAS4MTPIV"
  NODE_SEED = "SA2VINNOUIUFRV5JQN3K4GBEHE4VM6EVPNQP2GZIXDDBLONXTTSIVHGW"
[WHITE_LIST]
  [WHITE_LIST.uk]
  PARTICIPANT_DOMAIN = "uk.one.payments.gftn.io"
  [WHITE_LIST.au]
  PARTICIPANT_DOMAIN = "au.one.payments.gftn.io"
